services: 
  postgres: 
    container_name: gt-postgres 
    # image: postgres:latest 
    build: ./postgres
    ports: 
      - "5432:5432"
    env_file: ".env"
    # environment: 
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      # - ./list_plantf.csv:/tmp/list_plantf.csv 
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
      - pgdata:/var/lib/postgresql/data 
    restart: always 

  pgadmin: 
    container_name: gt-pgadmin
    # image: dpage/pgadmin4:latest
    build: ./pgadmin
    depends_on: 
      - postgres
    ports:
      - "5050:80" 
    env_file: ".env"
    # environment: 
    #   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    #   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: always
  
  fastapi:
    container_name: gt-fastapi
    build: ./fastapi
    depends_on: 
      - postgres
    ports:
      - "80:80"
    env_file: ".env"
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_NETLOC=${POSTGRES_NETLOC}
    restart: always
  
volumes: 
  pgdata: