services: 
  postgres: 
    container_name: gt-postgres 
    build: ./postgres
    ports: 
      - "5432:5432"
    env_file: ".env"
    volumes: 
      - pgdata:/var/lib/postgresql/data 
    restart: always 

  # "11434:11434"
  # -v ollama:/root/.ollama
  # Ollama API
  ollama:
    container_name: gt-ollama
    build: 
      context: ./ollama 
      args:
        - OLLAMA_MODEL_NAME=llama3.1:8b
    ports: 
      - "11434:11434"
    env_file: ".env"
    volumes:
      - ollama:/root/.ollama
    restart: always

  pgadmin: 
    container_name: gt-pgadmin
    build: ./pgadmin
    depends_on: 
      - postgres
    ports:
      - "5050:80" 
    env_file: ".env"
    restart: always

  # "3001:8080"
  # -v open-webui:/app/backend/data
  # OpenWeb UI
  openwebui:
    container_name: gt-openwebui
    build: ./openwebui
    depends_on:
      - ollama
    ports:
      - "3001:8080"
    env_file: ".env"
    volumes:
      - open-webui:/app/backend/data
    restart: always
  
  fastapi:
    container_name: gt-fastapi
    build: ./fastapi
    depends_on: 
      - postgres
    ports:
      - "80:80"
    env_file: ".env"
    restart: always
  
  react:
    container_name: gt-react
    build: ./react
    depends_on:
      - fastapi
    ports:
      - "3000:3000"
    env_file: ".env"
    restart: always
  
volumes: 
   pgdata:
   ollama:
   open-webui: